# Generated by Django 6.0.4 on 2026-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, help_text='Previous status of the booking before the change.', max_length=40)),
                ('new_status', models.CharField(help_text='New status of the booking after the change.', max_length=40)),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the status change, such as reasons for cancellation or notes on confirmation.')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the status was changed.')),
            ],
            options={
                'db_table': 'booking_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
