services:
  db:
    image: postgres:16
    container_name: nightos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nightos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      # Map container PostgreSQL port to 5433 on host
      # to avoid conflict with local PostgreSQL on 5432
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: