# Generated by Django 6.0.4 on 2026-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone'), ('others', 'Others')], default='whatsapp', help_text='Method of contact used for this communication attempt.', max_length=20)),
                ('contact_date', models.DateField(help_text='Date when the contact attempt was made.')),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('replied', 'Replied'), ('no_response', 'No Response'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('follow_up_needed', 'Follow-up Needed')], help_text='Result of the communication attempt.', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact attempt, such as details of the conversation or next steps.')),
                ('contacted_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the contact log entry was recorded.')),
            ],
            options={
                'db_table': 'booking_contact_logs',
                'ordering': ['-contact_date'],
            },
        ),
    ]
