# Generated by Django 6.0.4 on 2026-04-20 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_contact_log', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcontactlog',
            name='booking',
            field=models.ForeignKey(help_text='Booking related to the communication attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingcontactlog',
            name='contacted_by',
            field=models.ForeignKey(blank=True, help_text='User who contacted the DJ or client.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
