# Generated by Django 6.0.4 on 2026-04-21 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_contact_log', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcontactlog',
            name='contacted_at',
        ),
        migrations.AddField(
            model_name='bookingcontactlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the contact log entry was created.'),
            preserve_default=False,
        ),
    ]
