# Generated by Django 6.0.4 on 2026-04-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Display name of the genre (e.g., Afrobeat, House Music, Techno, Hip-Hop, Shatta,  Bouyon).', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Stable unique identifier used in filtering and URLs.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional internal description of the genre (eg. generalist).')),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('full_name', models.CharField(help_text='Legal or full name of the DJ.', max_length=150)),
                ('stage_name', models.CharField(blank=True, help_text='Public/stage name used for events.', max_length=150, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact number, often used for Whatsapp communication.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional email address.', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about preferences or operational comments.')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate the DJ without deleting historical bookings.')),
                ('genres', models.ManyToManyField(blank=True, help_text='Musical genres associated with the DJ.', related_name='djs', to='djs.genre')),
            ],
            options={
                'db_table': 'djs',
                'ordering': ['stage_name', 'full_name'],
            },
        ),
    ]
