# Generated by Django 6.0.4 on 2026-04-20 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('login', 'Login'), ('failed_login', 'Failed Login')], help_text='Type of action performed by the user.', max_length=30)),
                ('target_model', models.CharField(help_text='Name of the model affected by the action (e.g., Booking, DJ, Venue).', max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Identifier of the affected record.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Humaan-readable description of the action.')),
                ('old_data', models.JSONField(blank=True, help_text='Optional Snapshot of the relevant data before the change.', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Optional Snapshot of the relevant data after the change.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed, if available.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User responsible for the action, if available.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='audit_log_action__ff81b5_idx'), models.Index(fields=['target_model'], name='audit_log_target__8ebda4_idx'), models.Index(fields=['-created_at'], name='audit_log_created_e49a79_idx')],
            },
        ),
    ]
