# Generated by Django 6.0.4 on 2026-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Public venue name shown in the platform.', max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='Stable unique identifier used in URLs and filtering.', max_length=150, unique=True)),
                ('city', models.CharField(blank=True, help_text='City where the venue is located.', max_length=100)),
                ('address', models.CharField(help_text='Venue address, optional for the MVP.', max_length=255)),
                ('timezone', models.CharField(blank=True, help_text='Timezone of the venue, used for scheduling and date/time logic.', max_length=64)),
            ],
            options={
                'db_table': 'venue',
                'ordering': ['name'],
            },
        ),
    ]
