# Generated by Django 6.0.4 on 2026-04-20 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djs', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('booking_date', models.DateField(help_text='Date of the booking.')),
                ('start_time', models.TimeField(blank=True, help_text='Scheduled start time for the booking.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Scheduled end time for the booking.', null=True)),
                ('event_title', models.CharField(blank=True, help_text='Optional title or description of the event.', max_length=200)),
                ('status', models.CharField(choices=[('to_book', 'To Book'), ('pending_dj_confirmation', 'Pending DJ Confirmation'), ('pending_client_confirmation', 'Pending Client Confirmation'), ('confirmed', 'Confirmed'), ('validated_change', 'Validated Change'), ('unusual_schedule', 'Unusual Schedule'), ('cancelled', 'Cancelled')], default='to_book', help_text='Operational booking status used in the confirmation workflow.', max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the booking, such as client preferences or special instructions.')),
                ('unusual_hours', models.BooleanField(default=False, help_text='Marks bookings with unusual or exceptional schedule hours.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('dj', models.ForeignKey(blank=True, help_text='Assigned DJ. Can be empty while the slot is still open.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='djs.dj')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Venue where the booking take place.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['booking_date', 'start_time'],
                'indexes': [models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'), models.Index(fields=['status'], name='bookings_status_51373b_idx')],
            },
        ),
    ]
