# Generated by Django 6.0.4 on 2026-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable a venue without deleting historical data.'),
        ),
    ]
